---
- name: ensure needed dependencies are installed
  apt:
    name:
      - cups
      - expect
      - lib32z1
      - lib32ncurses5
      - lib32stdc++6
  when: ansible_os_family == "Debian"
  tags: ["packages","brother"]

- name: ensure tmp dir exist
  file: path={{brother_install_dir}} state=directory
  tags: ["packages","brother"]

- name: download brother install tool
  get_url: url={{brother_install_tool_url}} dest={{brother_install_dir}}
  tags: ["packages","brother"]

- name: extract brother install tool
  command: gunzip {{brother_install_dir}}/{{brother_install_tool_archive}} creates={{brother_install_dir}}/{{brother_install_tool_bin}} 
  tags: ["packages","brother"]

- name: ensure brother install is executable
  file: path={{brother_install_dir}}/{{brother_install_tool_bin}} mode=755
  tags: ["packages","brother"]

- name: create symlink
  file: state=link src={{brother_install_dir}}/{{brother_install_tool_bin}} path={{brother_bin_dir}}/linux-brprinter-installer
  tags: ["packages","brother"]

- name: install and configure printers
  shell: |
    # Exit without changes if the printer is already installed
    set timeout 2
    spawn /usr/bin/lpstat -a
    expect {
        "{{item.name}}" { exit 4 }
        timeout {}
    }

    # Set larger timeout to wait for updates and cupsd restart
    set timeout 180

    # Run Brother script for printer
    spawn {{brother_bin_dir}}/linux-brprinter-installer {{item.name}}

    expect {
        "OK?" {
            send "y\r"
            exp_continue
        }
        "Do you agree" {
            send "Y\r"
            exp_continue
        }
        "specify the Device URI" {
            send "Y\r"
            exp_continue
        }
        "number of destination Device URI" {
            send "I\r"
            exp_continue
        }
        "enter IP address" {
            send "{{item.ip}}\r"
            exp_continue
        }
        "Test Print" {
            send "N\r"
            exp_continue
        }
        "Hit Enter" {
            send "\r"
            exp_continue
        }
        eof {}
    }
  args:
    executable: /usr/bin/expect
    chdir: /tmp
  with_items: "{{brother_printers_to_install}}"
  register: response
  changed_when: response.rc == 0
  failed_when: response.rc != 0 and response.rc != 4
  tags: ["packages","brother"]
